<?php

namespace Database\Seeders;

use App\Models\Kelurahan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Aceh
        $aceh_barat_arongan_malabek = [
            "Arongan",
            "Cot Buloh",
            "Cot Kumbang",
            "Drien Rampak",
            "Keub",
            "Kubu",
            "Pante Mutia",
            "Peuribu",
            "Seuneubok Lhong",
            "Suak Bidok",
            "Suak Ie Beuso",
            "Suak Keumudai",
            "Teupin Peuraho",
            "Ujong Beusa",
            "Alue Bagok",
            "Alue Batee",
            "Alue Sundak",
            "Cot Juru Mudi",
            "Gunong Pulo",
            "Karang Hampa",
            "Panton Bahagia",
            "Panton Makmur",
            "Peulanteu",
            "Rimba Langgeh",
            "Seuneubok Teungoh",
            "Simpang Peut",
            "Ujong Simpang",
        ];

        $aceh_barat_bubon = [
            "Alue Bakong",
            "Alue Lhok",
            "Beurawang",
            "Blang Sibeutong",
            "Cot Keumuneng",
            "Cot Lada",
            "Gunong Panah",
            "Kuala Pling",
            "Kuta Padang",
            "Layung",
            "Liceh",
            "Peulanteu",
            "Rambong",
            "Seumuleng",
            "Seuneubok Trap",
            "Suak Pangkat",
            "Ulee Blang",
        ];

        $aceh_barat_johan_pahlawan = [
            "Blang Beurandang",
            "Drien Rampak",
            "Gampa",
            "Kampung Belakang",
            "Kampung Darat",
            "Kampung Pasir",
            "Kuta Padang",
            "Lapang",
            "Leuhan",
            "Padang Seurahet",
            "Panggong",
            "Pasar Aceh",
            "Rundeng",
            "Seuneubok",
            "Suak Nie",
            "Suak Raya",
            "Suak Ribee",
            "Suak Sigadeng",
            "Suak Indrapuri",
            "Ujong Baroh",
            "Ujung Kalak",
        ];

        $aceh_barat_kaway_xvi = [
            "Alue Lhok",
            "Padang Sikabu",
            "Sawang Teubei",
            "Alue On",
            "Blang Geunang",
            "Batu Jaya",
            "Meunasah Gantung",
            "Meunasah Rambot",
            "Muko",
            "Palimbungan",
            "Pasi Jeumpa",
            "Putim",
            "Puuk",
            "Tanjong Bungong",
            "Alue Tampak",
            "Beureugang",
            "Kampung Mesjid",
            "Keude Aron",
            "Marek",
            "Meunasah Ara",
            "Meunasah Buloh",
            "Meunasah Rayeuk",
            "Padang Mancang",
            "Pasi Jambu",
            "Pasi Teungoh",
            "Peunia",
            "Simpang",
            "Tumpok Ladang",
            "Alue Lhee",
            "Alue Peudeung",
            "Babah Meulaboh",
            "Blang Dalam",
            "Drien Caleu",
            "Keude Tanjong",
            "Keuramat",
            "Meunuang Tanjong",
            "Pasi Ara",
            "Pasi Kumbang",
            "Pasi Meugat",
            "Pucok Pungkie",
            "Pungkie",
            "Tanjong Meulaboh",
            "Teladan",
            "Teupin Panah",
        ];

        $aceh_barat_meureubo = [
            "Bukit Jaya",
            "Balee",
            "Gunong Kleng",
            "Langung",
            "Meureubo",
            "Paya Peunaga",
            "Peunaga Cut Ujong",
            "Peunaga Pasi",
            "Peunaga Rayeuk",
            "Pucok Reudeup",
            "Reudeup",
            "Sumber Batu",
            "Ujong Drien",
            "Ujong Tanjung",
            "Mesjid Tuha",
            "Buloh",
            "Pasi Aceh Baroh",
            "Pasi Aceh Tunong",
            "Pasi Mesjid",
            "Pasi Pinang",
            "Paya Baro Ranto Panyang",
            "Pulo Teungoh Ranto Panyang",
            "Ranto Panyang Barat",
            "Ranto Panyang Timur",
            "Ranub Dong",
            "Ujong Tanoh Darat",
        ];

        $aceh_barat_pantai_ceureumen = [
            "Babah Krueng Tep Lep",
            "Berdikari",
            "Gunong Tarok",
            "Keude Suak Awe",
            "Krueng Beukah",
            "Lhok Guci",
            "Lhok Sari",
            "Sawang Rambot",
            "Suak Awe",
            "Tegal Sari",
            "Canggei",
            "Lango",
            "Lawet",
            "Sikundo",
            "Jambak",
            "Keutambang",
            "Manjeng",
            "Pante Ceureumen",
            "Pulo Teungoh Manyang",
            "Alue Keumang",
            "Babah Iseung",
            "Babah Lueng",
            "Meunuang Kinco",
            "Seumantok",
            "Seumara",
        ];

        $aceh_barat_panon_reu = [
            "Antong",
            "Babah Krueng Manggie",
            "Baro Paya",
            "Blang Balee",
            "Blang Teungoh",
            "Cot Manggie",
            "Gampong Baro",
            "Gunung Mata Ie",
            "Kuala Manye",
            "Lek Lek",
            "Manggie",
            "Meutulang",
            "Mugo Cut",
            "Mugo Rayeuk",
            "Paya Baro Meuko",
            "Sibintang",
            "Tamping",
            "Tuwi Buya",
            "Ujong Raja",
        ];

        $aceh_barat_samatiga = [
            "Krueng Tinggai",
            "Leubok",
            "Deuah",
            "Pange",
            "Gampong Cot",
            "Lhok Bubon",
            "Suak Geudubang",
            "Suak Pandan",
            "Suak Pante Breuh",
            "Suak Seuke",
            "Suak Seumaseh",
            "Cot Amun",
            "Leukeun",
            "Mesjid Baro",
            "Keureuseng",
            "Cot Darat",
            "Cot Pluh",
            "Cot Seumeureng",
            "Cot Mesjid",
            "Paya Lumpat",
            "Suak Timah",
            "Cot Lampise",
            "Gampong Ladang",
            "Pinem",
            "Rangkileh",
            "Reusak",
            "Ujong Nga",
            "Alue Raya",
            "Cot Seulamat",
            "Gampong Teungoh",
            "Kuala Bubon",
            "Pucok Lueng",
        ];

        $aceh_barat_sungai_mas = [
            "Gaseu",
            "Gleung",
            "Gunong Buloh",
            "Leubok Beutong",
            "Lueng Baro",
            "Pungkie",
            "Ramitie",
            "Sipot",
            "Tanoh Mirah",
            "Drien Sibak",
            "Geudong",
            "Kajeung",
            "Lancong",
            "Sakuy",
            "Sarah Perlak",
            "Tungkop",
            "Tutut",
            "Tuwi Saya",
        ];

        $aceh_barat_woyla = [
            "Cot Lagan Bubon/CM",
            Cot Murong",
            Glee Siblah",
            Suak Tring",
            Alue Panyang",
            Alue Sundak",
            Bakat",
            Cot Keumudee",
            Cot Situah",
            Jawa",
            Jawi",
            Keuleumbah",
            Panton",
            Pasi Birah",
            Pulo Ie",
            Seumantok",
            Teumarom",
            Alue Blang",
            Alue Sikaya",
            Aron Baroh",
            Aron Tunong",
            Blang Mee",
            Darul Huda",
            Drin Mangko",
            Gempa Raya",
            Gunong Rambong",
            Gunung Hampa",
            Ie Itam Baroh",
            Ie Itam Tunong",
            Kuala Bhee",
            Lueng Buloh",
            Lueng Tanoh Tho",
            Lueng Teungku Yah",
            Lung Jawa",
            Padang Jawa",
            Pasi Aceh",
            Pasi Ara Kuala Batee",
            Pasi Lunak",
            Pasi Pandan",
            Paya Dua",
            Paya Luah",
            Ranto Panyang",
            Tingkeum Panyang",
        ];

        // Aceh
        foreach ($aceh_barat_arongan_malabek as $a) {
            Kelurahan::create([
                'kelurahan' => $a,
                'kec_code' => 1,
                'created_by' => 'Seeder',
                'updated_by' => 'Seeder',
            ]);
        }

        foreach ($aceh_barat_bubon as $a) {
            Kelurahan::create([
                'kelurahan' => $a,
                'kec_code' => 2,
                'created_by' => 'Seeder',
                'updated_by' => 'Seeder',
            ]);
        }

        foreach ($aceh_barat_johan_pahlawan as $a) {
            Kelurahan::create([
                'kelurahan' => $a,
                'kec_code' => 3,
                'created_by' => 'Seeder',
                'updated_by' => 'Seeder',
            ]);
        }
    }
}
