<?php

namespace Database\Seeders\Master;

use App\Models\Master\Kota as MasterKota;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $name = [
            "KAB ACEH SELATAN",
            "KAB ACEH TIMUR",
            "KAB ACEH TENGAH",
            "KAB ACEH BARAT",
            "KAB ACEH BESAR",
            "KAB PIDIE",
            "KAB ACEH UTARA",
            "KAB ACEH SINGKIL",
            "KAB BIREUEN",
            "KAB ACEH BARAT DAYA",
            "KAB ACEH JAYA",
            "KAB NAGAN RAYA",
            "KAB ACEH TAMIANG",
            "KAB BENER MERIAH",
            "KOTA BANDA ACEH",
            "KOTA SABANG",
            "KOTA LHOKSUMAWE",
            "KOTA LANGSA",
            "KAB TAPANULI TENGAH",
            "KAB TAPANULI UTARA",
            "KAB TAPANULI SELATAN",
            "KAB LANGKAT",
            "KAB DELI SERDANG",
            "KAB SIMALUNGUN",
            "KAB ASAHAN",
            "KAB LABUHAN BATU",
            "KAB DAIRI",
            "KAB TOBA SAMOSIR",
            "KAB MANDAILING NATAL",
            "KAB MUMBANG MASUNDUTAN",
            "KAB TOBA SAMOSIR",
            "KAB SERDANG BEDAGAI",
            "KOTA MEDAN",
            "KOTA PEMATANG SIANTAR",
            "KOTA SIBOLGA",
            "KOTA TANJUNG BALAI",
            "KOTA BINJAI",
            "KOTA TEBING TINGGI",
            "KOTA PADANG SIDEMPUAN",
            "KAB KEPULAUAN MENTAWAI",
            "KAB PESISIR SELATAN",
            "KAB SOLOK",
            "KAB SAWAHLUNTO/SIJUNJUNG",
            "KAB TANAH DATAR",
            "KAB PADANG PARIAMAN",
            "KAB AGAM",
            "KAB LIMA PULUH KOTA",
            "KAB PASAMAN TIMUR",
            "KAB DHARMASRAYA",
            "KAB SOLOK SELATAN",
            "KAB PASAMAN BARAT",
            "KAB ERROR",
            "KOTA PADANG",
            "KOTA SOLOK",
            "KOTA SAWAHLUNTO",
            "KOTA PADANG PANJANG",
            "KOTA BUKITTINGGI",
            "KOTA PAYAKUMBUH",
            "KOTA PARIAMAN",
            "KAB KAMPAR",
            "KAB INDRAGIRI HULU",
            "KAB BENGKALIS",
            "KAB INDRAGIRI HILIR",
            "KAB PELALAWAN",
            "KAB ROKAN HULU",
            "KAB ROKAN HILIR",
            "KAB SIAK",
            "KAB KUANTAN SENGINGI",
            "KOTA PEKAN BARU",
            "KOTA DUMAI",
            "KAB KERINCI",
            "KAB MERANGIN",
            "KAB SAROLANGUN",
            "KAB BATANG HARI",
            "KAB MUARO JAMBI",
            "KAB TANJUNG JABUNG BARAT",
            "KAB TANJUNG JABUNG TIMUR",
            "KAB BUNGO",
            "KAB TEBO",
            "KOTA JAMBI",
            "KAB OGAN KOMERING ULU",
            "KAB OGAN KOMERING ILIR",
            "KAB MUARA ENIM",
            "KAB LAHAT",
            "KAB MUSI RAWAS",
            "KAB MUSI BANYU ASIN",
            "KAB BANYU ASIN",
            "KAB OGAN KOMERING ULU SELATAN",
            "OKUT",
            "KAB OGAN ILIR",
            "KOTA PALEMBANG",
            "KOTA PAGAR ALAM",
            "KOTA LUBUK LINGGAU",
            "KOTA PRABUMULIH",
            "KAB BENGKULU SELATAN",
            "KAB REJANG LEBONG",
            "KAB BENGKULU UTARA",
            "KABBENGKULU UTARA",
            "KAB SELUMA",
            "KAB MUKO MUKO",
            "KAB LEBONG",
            "KAB KEPAHIANG",
            "KOTA BENGKULU",
            "KAB LAMPUNG SELATAN",
            "KAB LAMPUNG TENGAH",
            "KAB LAMPUNG UTARA",
            "KAB LAMPUNG BARAT",
            "KAB TULANG BAWANG",
            "KAB TANGGAMUS",
            "KAB LAMPUNG TIMUR",
            "KAB WAY KANAN",
            "KOTA BANDAR LAMPUNG",
            "KOTA METRO",
            "KAB BANGKA",
            "KAB BELITUNG",
            "KAB BANGKA SELATAN",
            "KAB BANGKA TENGAH",
            "KAB BANGKA BARAT",
            "KAB BELITUNG TIMUR",
            "KOTA PANGKAL PINANG",
            "KAB KEPULAUAN RIAU",
            "KAB KARIMUN",
            "KAB NATUNA",
            "KAB LINGGA",
            "KOTA BATAM",
            "KOTA TANJUNG PINANG",
            "KODYA JAKARTA PUSAT",
            "KODYA JAKARTA UTARA",
            "KODYA JAKARTA BARAT",
            "KODYA JAKARTA SELATAN",
            "KODYA JAKARTA TIMUR",
            "KAB BOGOR",
            "KAB SUKABUMI",
            "KAB CIANJUR",
            "KAB BANDUNG",
            "KAB GARUT",
            "KAB TASIKMALAYA",
            "KAB CIAMIS",
            "KAB KUNINGAN",
            "KAB CIREBON",
            "KAB MAJALENGKA",
            "KAB SUMEDANG",
            "KAB INDRAMAYU",
            "KAB SUBANG",
            "KAB PURWAKARTA",
            "KAB KARAWANG",
            "KAB BEKASI",
            "KOTA BOGOR",
            "KOTA SUKABUMI",
            "KOTA BANDUNG",
            "KOTA CIREBON",
            "KOTA BEKASI",
            "KOTA DEPOK",
            "KOTA CIMAHI",
            "KOTA TASIKMALAYA",
            "KOTA BANJAR",
            "KAB CILACAP",
            "KAB BANYUMAS",
            "KAB PURBALINGGA",
            "KAB BANJARNEGARA",
            "KAB KEBUMEN",
            "KAB PURWOREJO",
            "KAB WONOSOBO",
            "KAB MAGELANG",
            "KAB BOYOLALI",
            "KAB KLATEN",
            "KAB SUKOHARJO",
            "KAB WONOGIRI",
            "KAB KARANGANYAR",
            "KAB SRAGEN",
            "KAB GROBOGAN",
            "KAB BLORA",
            "KAB REMBANG",
            "KAB PATI",
            "KAB KUDUS",
            "KAB JEPARA",
            "KAB DEMAK",
            "KAB SEMARANG",
            "KAB TEMANGGUNG",
            "KAB KENDAL",
            "BATANG",
            "PEKALONGAN",
            "PEMALANG",
            "KAB TEGAL",
            "KAB BREBES",
            "KOTA MAGELANG",
            "KOTA SURAKARTA",
            "KOTA SALATIGA",
            "KOTA SEMARANG",
            "KOTA PEKALONGAN",
            "KOTA TEGAL",
            "KAB KULONPROGO",
            "KAB BANTUL",
            "KAB GUNUNG KIDUL",
            "KAB SLEMAN",
            "KOTA YOGYAKARTA",
            "KAB PACITAN",
            "KAB PONOROGO",
            "KAB TRENGGALEK",
            "KAB TULUNGAGUNG",
            "KAB BLITAR",
            "KAB KEDIRI",
            "KAB MALANG",
            "KAB LUMAJANG",
            "KAB JEMBER",
            "KAB BANYUWANGI",
            "KAB BONDOWOSO",
            "KAB SITUBONDO",
            "KAB PROBOLINGGO",
            "KAB PASURUAN",
            "KAB SIDOARJO",
            "KAB MOJOKERTO",
            "KAB JOMBANG",
            "KAB NGANJUK",
            "KAB MADIUN",
            "KAB MAGETAN",
            "KAB NGAWI",
            "KAB BOJONEGORO",
            "KAB TUBAN",
            "KAB LAMONGAN",
            "KAB GRESIK",
            "KAB BANGKALAN",
            "KAB SAMPANG",
            "KAB PAMEKASAN",
            "KAB SUMENEP",
            "KOTA KEDIRI",
            "KOTA MALANG",
            "KOTA PROBOLINGGO",
            "KOTA PASURUAN",
            "KOTA MADIUN",
            "KOTA SURABAYA",
            "KOTA BATU",
            "KOTA MOJOKERTO",
            "KAB PANDEGLANG",
            "KAB LEBAK",
            "KAB TANGERANG",
            "KAB SERANG",
            "KOTA CILEGON",
            "KOTA TANGERANG",
            "KOTA CILEGON",
            "KOTA TANGERANG SELATAN",
            "KAB JEMBRANA",
            "KAB TABANAN",
            "KAB BADUNG",
            "KAB GIANYAR",
            "KAB KLUNGKUNG",
            "KAB BANGLI",
            "KAB KARANG ASEM",
            "KAB BULELENG",
            "KOTA DENPASAR",
            "KAB LOMBOK BARAT",
            "KAB LOMBOK TENGAH",
            "KAB LOMBOK TIMUR",
            "KAB SUMBAWA",
            "KAB DOMPU",
            "KAB BIMA",
            "KAB SUMBAWA BARAT",
            "KOTA MATARAM",
            "KOTA BIMA",
            "KAB KUPANG",
            "KAB TIMOR TENGAH SELATAN",
            "KAB TIMOR TENGAH UTARA",
            "KAB BELU",
            "KAB ALOR",
            "KAB FLORES TIMUR",
            "KAB SIKKA",
            "KAB ENDE",
            "KAB NGADA",
            "KAB MANGGARAI",
            "KAB LEMBATA",
            "KAB MANGGARAI BARAT",
            "KOTA KUPANG",
            "KAB SAMBAS",
            "KAB KUBU RAYA",
            "KAB SANGGAU",
            "KAB KETAPANG",
            "KAB SINTANG",
            "KAB KAPUAS HULU",
            "KAB BENGKAYANG",
            "KAB LANDAK",
            "KAB MELAWI",
            "KAB SEKADAU",
            "KOTA PONTIANAK",
            "KOTA SINGKAWANG",
            "KAB KOTA WARINGIN BARAT",
            "KAB KOTA WARINGIN TIMUR",
            "KAB KAPUAS",
            "KAB BARITO SELATAN",
            "KAB BARITO UTARA",
            "KAB KATINGAN",
            "KAB SERUYAN",
            "KAB SUKAMARA",
            "KAB LAMANDAU",
            "KAB GUNUNG MAS",
            "KAB PULANG PISAU",
            "KAB MURUNG RAYA",
            "KAB BARITO TIMUR",
            "KOTA PALANGKA RAYA",
            "KAB TANAH LAUT",
            "KAB KOTA BARU",
            "KAB BANJAR",
            "KAB BARITO KUALA",
            "KAB TAPIN",
            "KAB HULU SUNGAI SELATAN",
            "KAB HULU SUNGAI TENGAH",
            "KAB BALANGAN",
            "KAB TABALONG",
            "KAB TANAH BUMBU",
            "KAB HULU SUNGAI UTARA",
            "KOTA BANJARMASIN",
            "KOTA BANJARBARU",
            "KAB PASIR",
            "KAB KUTAI KERTANEGARA",
            "KAB BERAU",
            "KAB BULUNGAN",
            "KAB NUNUKAN",
            "KAB MALINAU",
            "KAB KUTAI BARAT",
            "KAB KUTAI TIMUR",
            "KAB PENAJAM PAGAR UTARA",
            "KOTA BALIKPAPAN",
            "KOTA SAMARINDA",
            "KOTA TARAKAN",
            "KOTA BONTANG",
            "KAB BOLAANG MONGONDOW",
            "KAB MINAHASA",
            "KAB KEPULAUAN SANGIHE",
            "KAB KEPULAUAN TALAUD",
            "KAB MINAHASA SELATAN",
            "KAB MINAHASA UTARA",
            "KOTA MANADO",
            "KOTA BITUNG",
            "KOTA TOMOHON",
            "KAB BANGGAI",
            "KAB POSO",
            "KAB DONGGALA",
            "KAB TOLI TOLI",
            "KAB BUOL",
            "KAB MOROWALI",
            "KAB BANGGAI KEPULAUAN",
            "KAB PARIGI MOUTONG",
            "KAB TOJO UNA UNA",
            "KOTA PALU",
            "KAB SELAYAR",
            "KAB BULUKUMBA",
            "KAB BANTAENG",
            "KAB JENEPONTO",
            "KAB TAKALAR",
            "KAB GOWA",
            "KAB SINJAI",
            "KAB BONE",
            "KAB MAROS",
            "KAB PANGKAJENE KEPULAUAN",
            "KAB BARRU",
            "KAB SOPPENG",
            "KAB WAJO",
            "KAB SIDENRENG RAPPANG",
            "KAB PINRANG",
            "KAB ENREKANG",
            "KAB LUWU",
            "KAB TANA TORAJA",
            "KAB LUWU UTARA",
            "KAB LUWU TIMUR",
            "KOTA MAKASSAR",
            "KOTA PARE PARE",
            "KOTA PALOPO",
            "KAB KOLAKA",
            "KAB KONAWE KENDARI",
            "KAB MUNA",
            "KAB BUTON",
            "KAB KONAWE SELATAN",
            "KAB BOMBANA",
            "KAB BOMBANA",
            "KOTA KENDARI",
            "KOTA BAU BAU",
            "KAB GORONTALO",
            "KAB BOALEMO",
            "KAB BONE BOLANGO",
            "KAB PAHUWATO",
            "KOTA GORONTALO",
            "KAB MAMUJU UTARA",
            "KAB MAMUJU",
            "KAB MAMASA",
            "KAB POLEWALI MAMASA",
            "KAB MAJENE",
            "KAB MALUKU TENGAH",
            "KAB MALUKU TENGGARA",
            "KAB MALUKU TENGGARA BARAT",
            "KAB BURU",
            "KAB SERAM BAGIAN TIMUR",
            "KAB SERAM BAGIAN BARAT",
            "KAB KEPULAUAN ARU",
            "KOTA AMBON",
            "KAB HALMAHERA BARAT",
            "KAB HALMAHERA TENGAH",
            "KAB HALMAHERA UTARA",
            "KAB HALMAHERA SELATAN",
            "KAB KEPULAUAN SULA",
            "KAB HALMAHERA TIMUR",
            "KOTA TERNATE",
            "KAB TIDORE KEPULAUAN",
            "KAB MERAUKE",
            "KAB JAYAPURA",
            "KAB MIMIKA",
            "KAB KEEROM",
            "KOTA JAYAPURA",
            "KAB SORONG",
            "KAB MANOKWARI",
            "KAB SORONG SELATAN",
            "KOTA SORONG",
        ];

        $code = [
            "1101",
            "1103",
            "1104",
            "1105",
            "1106",
            "1107",
            "1108",
            "1110",
            "1111",
            "1112",
            "1114",
            "1115",
            "1116",
            "1117",
            "1171",
            "1172",
            "1173",
            "1174",
            "1201",
            "1202",
            "1203",
            "1205",
            "1207",
            "1208",
            "1209",
            "1210",
            "1211",
            "1212",
            "1213",
            "1216",
            "1217",
            "1218",
            "1271",
            "1272",
            "1273",
            "1274",
            "1275",
            "1276",
            "1277",
            "1301",
            "1302",
            "1303",
            "1304",
            "1305",
            "1306",
            "1307",
            "1308",
            "1309",
            "1310",
            "1311",
            "1312",
            "1313",
            "1371",
            "1372",
            "1373",
            "1374",
            "1375",
            "1376",
            "1377",
            "1401",
            "1402",
            "1403",
            "1404",
            "1405",
            "1406",
            "1407",
            "1408",
            "1409",
            "1471",
            "1472",
            "1501",
            "1502",
            "1503",
            "1504",
            "1505",
            "1506",
            "1507",
            "1508",
            "1509",
            "1571",
            "1601",
            "1602",
            "1603",
            "1604",
            "1605",
            "1606",
            "1607",
            "1608",
            "1609",
            "1610",
            "1671",
            "1672",
            "1673",
            "1674",
            "1701",
            "1702",
            "1703",
            "1704",
            "1705",
            "1706",
            "1707",
            "1708",
            "1771",
            "1801",
            "1802",
            "1803",
            "1804",
            "1805",
            "1806",
            "1807",
            "1808",
            "1871",
            "1872",
            "1901",
            "1902",
            "1903",
            "1904",
            "1905",
            "1906",
            "1971",
            "2101",
            "2102",
            "2103",
            "2104",
            "2171",
            "2172",
            "3171",
            "3172",
            "3173",
            "3174",
            "3175",
            "3201",
            "3202",
            "3203",
            "3204",
            "3205",
            "3206",
            "3207",
            "3208",
            "3209",
            "3210",
            "3211",
            "3212",
            "3213",
            "3214",
            "3215",
            "3216",
            "3271",
            "3272",
            "3273",
            "3274",
            "3275",
            "3276",
            "3277",
            "3278",
            "3279",
            "3301",
            "3302",
            "3303",
            "3304",
            "3305",
            "3306",
            "3307",
            "3308",
            "3309",
            "3310",
            "3311",
            "3312",
            "3313",
            "3314",
            "3315",
            "3316",
            "3317",
            "3318",
            "3319",
            "3320",
            "3321",
            "3322",
            "3323",
            "3324",
            "3325",
            "3326",
            "3327",
            "3328",
            "3329",
            "3371",
            "3372",
            "3373",
            "3374",
            "3375",
            "3376",
            "3401",
            "3402",
            "3403",
            "3404",
            "3471",
            "3501",
            "3502",
            "3503",
            "3504",
            "3505",
            "3506",
            "3507",
            "3508",
            "3509",
            "3510",
            "3511",
            "3512",
            "3513",
            "3514",
            "3515",
            "3516",
            "3517",
            "3518",
            "3519",
            "3520",
            "3521",
            "3522",
            "3523",
            "3524",
            "3525",
            "3526",
            "3527",
            "3528",
            "3529",
            "3571",
            "3573",
            "3574",
            "3575",
            "3577",
            "3578",
            "3579",
            "3580",
            "3601",
            "3602",
            "3603",
            "3604",
            "3610",
            "3671",
            "3672",
            "3674",
            "5101",
            "5102",
            "5103",
            "5104",
            "5105",
            "5106",
            "5107",
            "5108",
            "5171",
            "5201",
            "5202",
            "5203",
            "5204",
            "5205",
            "5206",
            "5207",
            "5271",
            "5272",
            "5301",
            "5302",
            "5303",
            "5304",
            "5305",
            "5306",
            "5307",
            "5308",
            "5309",
            "5310",
            "5313",
            "5315",
            "5371",
            "6101",
            "6102",
            "6103",
            "6104",
            "6105",
            "6106",
            "6107",
            "6108",
            "6109",
            "6110",
            "6171",
            "6172",
            "6201",
            "6202",
            "6203",
            "6204",
            "6205",
            "6206",
            "6207",
            "6208",
            "6209",
            "6210",
            "6211",
            "6212",
            "6213",
            "6271",
            "6301",
            "6302",
            "6303",
            "6304",
            "6305",
            "6306",
            "6307",
            "6308",
            "6309",
            "6310",
            "6311",
            "6371",
            "6372",
            "6401",
            "6402",
            "6403",
            "6404",
            "6405",
            "6406",
            "6407",
            "6408",
            "6409",
            "6471",
            "6472",
            "6473",
            "6474",
            "7101",
            "7102",
            "7103",
            "7104",
            "7105",
            "7106",
            "7171",
            "7172",
            "7173",
            "7201",
            "7202",
            "7203",
            "7204",
            "7205",
            "7206",
            "7207",
            "7208",
            "7209",
            "7271",
            "7301",
            "7302",
            "7303",
            "7304",
            "7305",
            "7306",
            "7307",
            "7308",
            "7309",
            "7310",
            "7311",
            "7312",
            "7313",
            "7314",
            "7315",
            "7316",
            "7317",
            "7318",
            "7322",
            "7324",
            "7371",
            "7372",
            "7373",
            "7401",
            "7402",
            "7403",
            "7404",
            "7405",
            "7406",
            "7407",
            "7471",
            "7472",
            "7501",
            "7502",
            "7503",
            "7504",
            "7571",
            "7601",
            "7602",
            "7603",
            "7604",
            "7605",
            "8101",
            "8102",
            "8103",
            "8104",
            "8105",
            "8106",
            "8107",
            "8171",
            "8201",
            "8202",
            "8203",
            "8204",
            "8205",
            "8206",
            "8271",
            "8272",
            "9101",
            "9103",
            "9109",
            "9111",
            "9171",
            "9201",
            "9202",
            "9204",
            "9271",
        ];

        $prov_code = [
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "12",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "13",
            "14",
            "14",
            "14",
            "14",
            "14",
            "14",
            "14",
            "14",
            "14",
            "14",
            "14",
            "15",
            "15",
            "15",
            "15",
            "15",
            "15",
            "15",
            "15",
            "15",
            "15",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "16",
            "17",
            "17",
            "17",
            "17",
            "17",
            "17",
            "17",
            "17",
            "17",
            "18",
            "18",
            "18",
            "18",
            "18",
            "18",
            "18",
            "18",
            "18",
            "18",
            "19",
            "19",
            "19",
            "19",
            "19",
            "19",
            "19",
            "21",
            "21",
            "21",
            "21",
            "21",
            "21",
            "31",
            "31",
            "31",
            "31",
            "31",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "32",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "33",
            "34",
            "34",
            "34",
            "34",
            "34",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "35",
            "36",
            "36",
            "36",
            "36",
            "36",
            "36",
            "36",
            "36",
            "51",
            "51",
            "51",
            "51",
            "51",
            "51",
            "51",
            "51",
            "51",
            "52",
            "52",
            "52",
            "52",
            "52",
            "52",
            "52",
            "52",
            "52",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "53",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "61",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "62",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "63",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "64",
            "71",
            "71",
            "71",
            "71",
            "71",
            "71",
            "71",
            "71",
            "71",
            "72",
            "72",
            "72",
            "72",
            "72",
            "72",
            "72",
            "72",
            "72",
            "72",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "73",
            "74",
            "74",
            "74",
            "74",
            "74",
            "74",
            "74",
            "74",
            "74",
            "75",
            "75",
            "75",
            "75",
            "75",
            "76",
            "76",
            "76",
            "76",
            "76",
            "81",
            "81",
            "81",
            "81",
            "81",
            "81",
            "81",
            "81",
            "82",
            "82",
            "82",
            "82",
            "82",
            "82",
            "82",
            "82",
            "91",
            "91",
            "91",
            "91",
            "91",
            "92",
            "92",
            "92",
            "92",
        ];

        DB::disableQueryLog();

        for ($i = 0; $i < count($name); $i++) {
            MasterKota::create([
                'kota_code' => $code[$i],
                'kota' => $name[$i],
                'prov_code' => $prov_code[$i],
                'is_active' => 'Y',
                'created_by' => 'Seeder',
                'updated_by' => 'Seeder',
            ]);
        }
    }
}
